package ru.simflex.ex.entities;

import javax.persistence.Entity;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;

/**
 * The PhoneNumber class represents phone number entity.
 *
 */
@Entity
@Table(name = "phonenumbers")
public class PhoneNumber {

    /**
     * Autogenerated ID of PhoneNumber entity.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "phonenumber_id")
    private int id;

    /**
     * Text form of phone number.
     */
    @Column(name = "phonenumber_string", nullable = false, unique = true)
    private String phoneNumberString;

    /**
     * Boolean variable represents is the phone number
     * is now available for usin or is used by some Contract entity.
     */
    @Column(name = "phonenumber_is_available")
    private boolean available;

    /**
     * Standart POJO getter.
     * @return ID of entity
     */
    public int getId() {
        return id;
    }

    /**
     * Standart POJO setter.
     * @param id ID of entity
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Standart POJO getter.
     * @return Text form of phone number
     */
    public String getPhoneNumberString() {
        return phoneNumberString;
    }

    /**
     * Standart POJO setter.
     * @param phoneNumberString Text form of phone number
     */
    public void setPhoneNumberString(String phoneNumberString) {
        this.phoneNumberString = phoneNumberString;
    }

    /**
     * Standart POJO getter.
     * @return Boolean variable of availability of a PhoneNumber
     */
    public boolean isAvailable() {
        return available;
    }

    /**
     * Standart POJO setter.
     * @param available Boolean variable of availability of a PhoneNumber
     */
    public void setAvailable(boolean available) {
        this.available = available;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null || getClass() != other.getClass()) {
            return false;
        }

        PhoneNumber option = (PhoneNumber) other;
        return this.getId() == option.getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        return id * 31;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "PhoneNumber{" +
                "id=" + id +
                ", phoneNumberString='" + phoneNumberString + '\'' +
                ", available=" + available +
                '}';
    }
}
